import React from 'react';

interface ReportTemplateProps {
  applicantName?: string;
  visaRoute: string;
  reportId?: string;
  date?: string;
}

type VerdictType = 'likely' | 'borderline' | 'unlikely';

const ReportTemplate: React.FC<ReportTemplateProps> = ({ 
  applicantName = "Valued Client", 
  visaRoute, 
  reportId = `CV-${Math.floor(100000 + Math.random() * 900000)}`,
  date = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
}) => {
  const [verdict, setVerdict] = React.useState<VerdictType>('borderline');
  const verdictContent = {
    likely: { title: "Likely eligible", text: "Meets key published requirements for this visa route.", colorClass: "emerald" },
    borderline: { title: "Borderline – risk factors present", text: "Answers suggest you may not clearly meet all requirements.", colorClass: "amber" },
    unlikely: { title: "Unlikely eligible", text: "One or more core requirements are not currently met.", colorClass: "rose" }
  };
  const content = verdictContent[verdict];

  return (
    <div className="a4-page bg-white shadow-2xl mx-auto p-[15mm] text-slate-800 max-w-[210mm] min-h-[297mm] flex flex-col font-sans relative overflow-hidden">
      <div className="watermark print-only uppercase tracking-[1em]">CLEARVISA UK – CONFIDENTIAL</div>

      <div className="flex justify-between items-start mb-12 relative z-10">
        <div className="flex-1">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 bg-navy text-white rounded-lg flex items-center justify-center font-serif text-2xl font-bold">C</div>
            <span className="text-[10px] font-black tracking-widest text-navy uppercase leading-tight">ClearVisa UK – Immigration<br/>Eligibility Pre-Check Report</span>
          </div>
          <h1 className="text-3xl font-black text-navy mb-2 uppercase tracking-tight leading-none">ClearVisa UK – Immigration Eligibility Pre-Check Report</h1>
          <p className="text-sm text-slate-500 max-w-md font-bold uppercase tracking-widest mt-2">CONFIDENTIAL ASSESSMENT</p>
        </div>
        <div className="bg-slate-50 p-6 rounded-xl border border-slate-100 text-[10px] font-bold min-w-[240px] uppercase tracking-wider">
          <div className="grid grid-cols-[auto,1fr] gap-x-4 gap-y-2">
            <span className="text-slate-400">Applicant:</span> <span className="text-navy">{applicantName}</span>
            <span className="text-slate-400">Route:</span> <span className="text-navy">{visaRoute}</span>
            <span className="text-slate-400">Date:</span> <span className="text-navy">{date}</span>
            <span className="text-slate-400">ID:</span> <span className="text-navy">{reportId}</span>
          </div>
        </div>
      </div>

      <div className="h-[2px] bg-slate-100 w-full mb-12 relative z-10"></div>

      <div className={`border-2 rounded-2xl p-8 text-center mb-12 relative z-10 border-${content.colorClass}-200 bg-${content.colorClass}-50`}>
        <h2 className={`text-2xl font-black uppercase tracking-widest mb-4 text-${content.colorClass}-800`}>{content.title}</h2>
        <p className={`text-base font-bold italic text-${content.colorClass}-700`}>{content.text}</p>
        <div className="mt-6 inline-block px-4 py-2 bg-white/50 rounded-lg text-[10px] font-black text-slate-500 uppercase tracking-widest">
          PRODUCED BY CLEARVISA UK ASSESSMENT ENGINE
        </div>
      </div>

      <div className="mb-12 relative z-10">
        <h3 className="text-sm font-black text-navy uppercase tracking-[0.2em] mb-4 border-b pb-2">Next Steps Recommended by ClearVisa UK</h3>
        <ul className="space-y-4">
          {["Gather evidence for Appendix FM compliance", "Address any flagged risk areas", "Consult OISC adviser for complex histories"].map((step, i) => (
            <li key={i} className="flex items-center gap-4 text-sm font-bold text-slate-700 bg-slate-50 p-3 rounded-lg border">
              <div className="w-2.5 h-2.5 rounded-full bg-accent"></div> {step}
            </li>
          ))}
        </ul>
      </div>

      <div className="bg-slate-50 p-8 rounded-2xl text-[11px] text-slate-500 border relative z-10 mt-auto font-bold uppercase tracking-wider leading-relaxed">
        <h4 className="font-black mb-3 text-navy">Legal Disclosure</h4>
        <p>ClearVisa UK – Immigration Eligibility Pre-Check Report is not a law firm. This assessment does not constitute legal advice. Final decisions are made solely by UKVI caseworkers. ClearVisa UK does not guarantee visa approval.</p>
      </div>

      <div className="mt-12 flex justify-between items-center text-[10px] text-slate-400 font-black tracking-[0.3em] uppercase pt-6 border-t relative z-10">
        <span>© 2024 ClearVisa UK</span>
        <span>CLEARVISA UK – CONFIDENTIAL</span>
        <span>Generated by ClearVisa UK</span>
      </div>
    </div>
  );
};

export default ReportTemplate;